In [3]:
import numpy as np
from numpy import *

In [5]:
random.rand(4,4)

array([[0.94857072, 0.66933497, 0.48856864, 0.05094151],
       [0.3309264 , 0.85574117, 0.81229961, 0.8440868 ],
       [0.13413999, 0.35610868, 0.91986933, 0.48585774],
       [0.52792972, 0.77848861, 0.16114887, 0.55029043]])

In [6]:
randMat = mat(random.rand(4,4))

In [7]:
randMat.I

matrix([[-216.04509089,  151.88054666,   32.3337802 ,   93.37972685],
        [ -69.13342881,   49.94054688,    9.37791076,   30.16353423],
        [  48.32892683,  -33.34992792,   -6.1513242 ,  -21.64980458],
        [ 162.27971403, -115.71753295,  -23.88098997,  -68.9836791 ]])

In [8]:
invRandMat = randMat.I

In [9]:
randMat*invRandMat

matrix([[ 1.00000000e+00,  0.00000000e+00,  1.77635684e-15,
          7.10542736e-15],
        [-7.10542736e-15,  1.00000000e+00,  8.88178420e-16,
          3.55271368e-15],
        [ 1.42108547e-14,  0.00000000e+00,  1.00000000e+00,
         -7.10542736e-15],
        [ 0.00000000e+00,  0.00000000e+00,  3.55271368e-15,
          1.00000000e+00]])